version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - static-code-analysis-3.10
      - test-3.8
      - test-3.9
      - test-3.10

defaults:
  working_directory: ~/code

jobs:
  static-code-analysis-3.10:
      docker:
      - image: circleci/python:3.10
      steps:
      - checkout
      - run:
          name: Prepare Environment
          command: pip install -r requirements_lint.txt
      - run:
          name: Black
          command: black --check .
      - run:
          name: Ruff
          command: ruff check --no-cache .
      - run:
          name: Mypy
          command: mypy

  test-3.8: &tests
      docker:
      - image: circleci/python:3.8
      steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt -r requirements_test.txt
      - run:
          name: Test
          command: pytest

  test-3.9:
      <<: *tests
      docker:
      - image: circleci/python:3.9

  test-3.10:
      <<: *tests
      docker:
      - image: circleci/python:3.10
