version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.5

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install -r requirements.txt
  - run:
      name: Test
      command: pytest

jobs:
  test-3.5:
    <<: *defaults
    docker:
    - image: circleci/python:3.5