version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: virtualenv venv
      - run: venv/bin/pip install -r requirements.txt
      - run: PYTHONPATH=. venv/bin/python tests/__init__.py
