version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - static-code-analysis-3.8
      - test-3.6
      - test-3.7
      - test-3.8

defaults:
  working_directory: ~/code

jobs:
  static-code-analysis-3.8:
      docker:
      - image: circleci/python:3.8
      steps:
      - checkout
      - run:
          name: Prepare Environment
          command: pip install -r requirements_lint.txt
      - run:
          name: Black
          command: black --check .
      - run:
          name: Ruff
          command: ruff check --no-cache .
      - run:
          name: Mypy
          command: mypy

  test-3.6: &tests
      docker:
      - image: circleci/python:3.6
      steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt -r requirements_test.txt
      - run:
          name: Test
          command: pytest

  test-3.7:
      <<: *tests
      docker:
      - image: circleci/python:3.7

  test-3.8:
      <<: *tests
      docker:
      - image: circleci/python:3.8
